### ISSUE TITLE
Missing dependency on YCM in documentation

### ISSUE THREAD

**Issue by traversaro** [robotology/wb-toolbox#100]
The wb-toolbox requires YCM to compile, but this dependency is not specified in the install documentation : https://github.com/robotology/wb-toolbox/blame/932c81cd049c7ce0c2494d60fe52bfd8c11dfd20/doc/mkdocs/data/install.md#L10 .

**Comment by diegoferigo** [comment]
Good catch, I ported recently the former dependency list to the website and YCM was missing also there. Happy issue #100! :tada:

**Comment by diegoferigo** [comment]
Fixed in https://github.com/robotology/wb-toolbox/commit/c50a0b3bbe79b257a8cf462c69ddb102c8d6a711.
