### ISSUE TITLE
Motor positions required in the JointsPosition block

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/wb-toolbox#104]
It would be very useful to be have a block for getting the **motor** positions/velocities/accelerations, the same way we can already get **joint** respective quantities. Typically, this is a critical requirement in the case we wish to control coupled joints PWMs independently depending on the motor positions. For instance when we are estimating coupled joints friction and motor parameters, this will allow us to perform the estimation motor axis wise instead of joint axis wise.

**Comment by nunoguedelha** [comment]
cc @diegoferigo

**Comment by diegoferigo** [comment]
Implemented in PR https://github.com/robotology/wb-toolbox/pull/110
