### ISSUE TITLE
When switching namespace yarpserver is not found

### ISSUE THREAD

**Issue by francesco-romano** [robotology/WB-Toolbox#12]
It happens systematically. A reboot of matlab is necessary to solve this issue.

**Comment by traversaro** [comment]
Was this the case also on the WBI-Toolbox 1.0 ?

**Comment by francesco-romano** [comment]
Never tested there.

**Comment by francesco-romano** [comment]
i found the responsible of this behaviour.
The resource finder always initialize the network, but the network is cleared only on the closing of the process which never occur on simulink.

We can move to not using ResourceFinder singletons.
Anyway we should wait for https://github.com/robotology/yarp/issues/1014

**Comment by francesco-romano** [comment]
cc @DanielePucci @S-Dafarra @gabrielenava it should be fixed now. 
Tell me if this is not true

**Comment by DanielePucci** [comment]
Great!
