### ISSUE TITLE
Error when double clicking on the yarp read/write block

### ISSUE THREAD

**Issue by gabrielenava** [robotology/wb-toolbox#122]
Every time I try to open the `yarp read` or `yarp write` block, I get this error:

![wbtoolbox_error](https://user-images.githubusercontent.com/12396934/40539127-034fe424-6014-11e8-933d-3a128d1e86c3.png)

If I press `ok` I can anyway edit the block.

**Comment by diegoferigo** [comment]
It is a minor mask error, I will fix it within the first Simulink Library commit I'll submit.

**Comment by gabrielenava** [comment]
Tested. It fixed the issue.
