### ISSUE TITLE
Yarp write block not working properly with the latest yarp devel

### ISSUE THREAD

**Issue by gabrielenava** [robotology/wb-toolbox#140]
I moved to the latest `devel` branch in YARP and icub-main. I tried to use the WBToolbox block `yarp write`, but it seems it is not working correctly anymore. In particular, while I am still able to send values when using the command: `yarp write ... /portname`, I am not able to perform the same operation using the toolbox. Therefore even if I strongly suspect the issue is related to a recent modification done in `yarp`, I guess that the issue is limited to the WBToolbox block. 

Unfortunately, I didn't see any error message in Simulink or on the terminal related to this issue.

**Comment by diegoferigo** [comment]
The problem is related YARP 3. The code of `YarpWrite` is very simple and right now it is not clear to me what could be the culprit.

**Comment by diegoferigo** [comment]
Fixed by #146 @gabrielenava
