### ISSUE TITLE
Set Reference block sets a fix default value for reference speed for joint movement in Position Control Mode

### ISSUE THREAD

**Issue by vibhoraggarwal** [robotology/wb-toolbox#149]
### Description:
- **Not able to change the reference speed** for moving the joint in `Position Control Mode` 
- Instead the block sets a default value,`10 rad/sec`,  for reference speed.
- Changing the speed from `yarpmotorgui` is working though.

@diegoferigo

**Comment by diegoferigo** [comment]
@vibhoraggarwal How did you check that the value didn't change? Note that the toolbox changes the reference speed only during the simulation, restoring the value found at its beginning when the simulation ends.

**Comment by vibhoraggarwal** [comment]
> How did you check that the value..

@diegoferigo I observed the value in `yarpmotorgui` during the operation. The value was set to `10`

**Comment by diegoferigo** [comment]
@vibhoraggarwal Can you please try the branch of PR #151? Those commits fix an unrelated error and on my setup the _Set References_ block works as expected. I do not exclude a strange link between the two given the randomness of the fixed bug.

**Comment by diegoferigo** [comment]
@vibhoraggarwal Did you manage to try the fix?

**Comment by vibhoraggarwal** [comment]
@diegoferigo Not yet. I plan to do it on Thursday.

**Comment by vibhoraggarwal** [comment]
@diegoferigo I tried the branch of PR #151 on `icubGenova02`. But the problem still persists; the reference velocity is still set to a default value of `10`

**Comment by diegoferigo** [comment]
I'll check on Monday on the robot. Similarly to #153 there is a mismatch between the simulated and the real robot.

**Comment by vibhoraggarwal** [comment]
@diegoferigo I see that you merged the `diegoferifo/fix/plugin` branch to `devel`. Now I tried again with the updated devel; the position control mode successfully updates the reference velocity for the joint's motion now. 
Unless @diegoferigo want to mention something about the issue, we can close it.

**Comment by diegoferigo** [comment]
Yes I merged the open PR since it was fixing a different (but related) bug. Probably something happened during checkouts when you did the tests last week because I didn't add any new commits. I'm glad to read that all works! :tada:
