### ISSUE TITLE
QP block stops the simulation if QP fails

### ISSUE THREAD

**Issue by gabrielenava** [robotology/wb-toolbox#158]
- [x] I already updated to the latest version I can use
- [x] I already checked similar issues using the search box
- [x] I already checked the website for known troubleshooting
- [x] I already cleaned my environment (by removing the wb-toolbox install folder and installing it again)
- [x] I already excluded the possibility that system configuration files (e.g. yarp related) might be responsible
- [x] I am sure the environment variables are correct
- [x] I tried to reproduce the error in simulation (if it affects the real robot)

#### Description

`QP` block  is supposed **not** to stop the simulation if the QP fails and the option `stop the simulation when the solver fails` is unchecked. Instead, even if the option is unchecked the simulation stops when the `QP` block fails to find a solution:

#### Platform

Verified in simulation with `icubGazeboSim` and `iCubGazeboV2_5`.

#### Reproducibility

`git clone` the [whole-body-controllers](https://github.com/robotology/whole-body-controllers) repository, `git checkout` the branch `WBToolbox4`, verify all the dependencies are correctly installed and run the `momentumBasedYoga` simulation.

#### Screenshots

![screenshot from 2018-08-22 17-20-17](https://user-images.githubusercontent.com/12396934/44473154-fcd08d80-a62f-11e8-845a-18fc33b4c5fd.png)

![screenshot from 2018-08-22 16-26-22](https://user-images.githubusercontent.com/12396934/44471083-73b75780-a62b-11e8-9a7b-7d779192d665.png)

![screenshot from 2018-08-22 16-50-08](https://user-images.githubusercontent.com/12396934/44471081-73b75780-a62b-11e8-96a2-c0da0b642a55.png)

#### Additional information

- OS: [Ubuntu 16.04]
- Version / Commit: [`v4.0`]
- Matlab Version: [ `2017b`]

**Comment by traversaro** [comment]
Downstream issue: https://github.com/robotology/whole-body-controllers/pull/3 .
