### ISSUE TITLE
Take gravity direction as a configurable option

### ISSUE THREAD

**Issue by DanielePucci** [robotology/WB-Toolbox#17]
The gravity direction used for computing the generalised bias forces is set internally, i.e. 

https://github.com/robotology/WB-Toolbox/blob/master/toolbox/src/InverseDynamics.cpp#L177

It would be desirable to get it as a configurable option.

@traversaro @nunoguedelha @francesco-romano

**Comment by nunoguedelha** [comment]
Maybe that's what you meant, but I think that it would be better if it was retrieved from the IMU measurement, to match Gazebo parameter.

**Comment by traversaro** [comment]
@nunoguedelha The "model" block are not supposed to read data directly , but they provide a flexible input structure such that the user can choose if hardcode the gravity or read it from the IMU.

**Comment by nunoguedelha** [comment]
ok, sure. Thanks

**Comment by francesco-romano** [comment]
Volunteers for testing?

**Comment by francesco-romano** [comment]
Closed by https://github.com/robotology/WB-Toolbox/pull/18
