### ISSUE TITLE
Significant error in Gravity Torque

### ISSUE THREAD

**Issue by VenusPasandi** [robotology/wb-toolbox#174]
I used the 'iCubGazeboV2_5 (no hands)' in the gazebo and control its position with 'set position'. Then, I compared the 'joint torques' and 'Gravity Torques' to check the gravity compensation. As you imagine, the Simulink model is simple as
![Screenshot from 2019-04-04 13-02-29](https://user-images.githubusercontent.com/34647611/55551065-25e2f180-56da-11e9-8a03-79648f607bf2.png)
The result is as
![untitled](https://user-images.githubusercontent.com/34647611/55551386-f5e81e00-56da-11e9-86a5-5e3068df146b.jpg)
There is a significant error between the gravity force and the joint torques!

**Comment by traversaro** [comment]
A few additional info:
* Which joints are you considering of the model (not the one that you are plotting, but all the joints that you specified in the WB-Toolbox configuration)? Remember that the joints you are not considering are assumed to be at their **zero** position w.r.t. to the computation of model quantities, including the gravity compensation torques. 
* Which model are you using in WB-Toolbox? Which model are you loading in Gazebo?

**Comment by VenusPasandi** [comment]
> Let's move this issue in WB-Toolbox.

Thanks @traversaro , I didn't know where is the best place to open this issue!

> Which model are you using in WB-Toolbox? Which model are you loading in Gazebo?

I checked the models in gazebo and wbt, the both are the same.

> Remember that the joints you are not considering are assumed to be at their zero position w.r.t. to the computation of model quantities, including the gravity compensation torques.

Yes, This is the problem! Previously, I considered the joints that I wanted to control in `config` block. Now I consider all the joints in the countrol board and the joint torques and the gravity forces match as following
![untitled](https://user-images.githubusercontent.com/34647611/55622350-44132500-57a0-11e9-8159-3f88fa54d42e.jpg)

thanks @traversaro

**Comment by diegoferigo** [comment]
cc @anqingd
