### ISSUE TITLE
Add OSQP block to deprecate the QpOases  block 

### ISSUE THREAD

**Issue by traversaro** [robotology/wb-toolbox#180]
#### Summary

It would be great to add a block for solving Quadratic Programming (QP) optimization problems using [OSQP](https://osqp.readthedocs.io/en/latest/index.html) (and optionally https://github.com/robotology/osqp-eigen) instead of the existing block that uses [qpOASES](https://projects.coin-or.org/qpOASES). 

#### Motivation
See https://github.com/robotology/robotology-superbuild/issues/239 on why it would be great to avoid the qpOASES dependency. 

#### Additional context

It may be even better to wrap in WB-Toolbox some generic interface with pluggable backend for QP programming, such as the one provided in iDynTree, Drake or RobOptim. However, this would be a bit more complex, and in the iDynTree case would also involve some work on the iDynTree side, while simple creating an OSQP block would be trivial, especially given that it already exists the QpOases block.

**Comment by traversaro** [comment]
Related comment from @diegoferigo : https://github.com/robotology-dependencies/qpOASES/issues/4#issuecomment-524298966 .

**Comment by traversaro** [comment]
Code of the existing block: 
* https://github.com/robotology/wb-toolbox/blob/f110c4b641a09a4bb392161db2ab79d0afc0adbe/toolbox/library/include/WBToolbox/Block/QpOases.h
* https://github.com/robotology/wb-toolbox/blob/f110c4b641a09a4bb392161db2ab79d0afc0adbe/toolbox/library/src/QpOases.cpp

**Comment by DanielePucci** [comment]
CC
@gabrielenava @S-Dafarra

**Comment by gabrielenava** [comment]
cc @CarlottaSartore

**Comment by nunoguedelha** [comment]
Hi @diegoferigo , could you assign this to me please, I can't do it myself.

**Comment by traversaro** [comment]
Done @nunoguedelha !

**Comment by traversaro** [comment]
@nunoguedelha I saw that the issue was in Ice-Box, I implemented a first version of it this morning.

**Comment by traversaro** [comment]
@diegoferigo `export_libraries` works nice also on Windows, cool:
![export_libraries](https://user-images.githubusercontent.com/1857049/118652958-608b4380-b7e7-11eb-8885-88113f26f347.PNG)
