### ISSUE TITLE
Release 5.1 

### ISSUE THREAD

**Issue by traversaro** [robotology/wb-toolbox#187]
#### Summary

Release 5.0 still use some legacy features of YCM that will be removed in the future, and even against YCM 0.11 create problems due (probably) to some YCM bug (see https://pipelines.actions.githubusercontent.com/ZuyQm6ovz1ad02r7CsxwF1VdDAwrcBAjuVSwcIMiZZdLCwGhMg/_apis/pipelines/1/runs/624/signedlogcontent/12?urlExpires=2020-04-25T16%3A46%3A10.6344990Z&urlSigningMethod=HMACV1&urlSignature=mvORgOxMB%2FlB80a8NvOYNk%2BA7gA3tC30%2FyxYEKCNyuU%3D). It would be great to have a 5.1 or 5.0.1 release that correspond to the last commit in the master branch.

#### Motivation

Mainly for https://github.com/robotology/robotology-superbuild/issues/387 .

**Comment by diegoferigo** [comment]
Thanks @traversaro for the reminder. I just released [`v5.1`](https://github.com/robotology/wb-toolbox/releases/tag/v5.1).
