### ISSUE TITLE
Re-implement the Holder block to make it compatible with code generation and "treat as atomic unit"

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/wb-toolbox#205]
#### Summary

<img width="113" alt="image" src="https://user-images.githubusercontent.com/6848872/116894487-62270a00-ac32-11eb-8827-de5efcd668ff.png">

Re-implement the Holder block (in "Utilities") in order to avoid the use of:
- persistent variables, which are incompatible with code generation.
- continuous blocks (the clock Simulink block): a sub-system combining discrete and continuous blocks cannot be treated as an atomic unit.

#### Motivation

Treating sub-systems as atomic units speed up the simulation and allow the use of different sampling times on multiple sub-systems without rate conversion problems.
Code generation increases the compilation time but improves significantly the runtime performance.

#### Additional context

The [whole-body-controllers/controllers/floating-base-balancing-torque-control](https://github.com/robotology/whole-body-controllers/tree/devel/controllers/floating-base-balancing-torque-control) model uses at least 7 Holder blocks.

**Comment by nunoguedelha** [comment]
## Block testing

<img width="729" alt="image" src="https://user-images.githubusercontent.com/6848872/118649104-68e17f80-b7e3-11eb-88a4-f270bffc5909.png">

The block was tested with a input vector of random signals. After execution, the scope should display constant values set to the first sample of the input signal generators.

## First Iteration
### Design
<img width="751" alt="image" src="https://user-images.githubusercontent.com/6848872/118650375-ab578c00-b7e4-11eb-87d8-e23188187020.png">

### MATLAB Function
```
function [memorized,y_n] = fcn(memorized,u_n,u_nm1)

% force output size to match input, otherwise Simulink sees it as variable sized output and
% fails compilation.
y_n = u_n;

if memorized
    y_n(:) = u_nm1; % expects u_nm1 to be y_n size
else
    y_n(:) = u_n;   % expects u_nm1 to be y_n size
end

memorized = true;
```

### Execution order
| root model level | Holder |
| --- | --- |
| <img width="735" alt="image" src="https://user-images.githubusercontent.com/6848872/118648844-215af380-b7e3-11eb-99ff-780ac31fa660.png"> | <img width="741" alt="image" src="https://user-images.githubusercontent.com/6848872/118648655-ef499180-b7e2-11eb-811b-837889e346a8.png"> |

This holder implementation worked fine and compiled properly the signal dimensions in a model with a single fixed sample time for ll blocks.
But once integrated in a model with multiple fixed sample times, the compilation fails after assigning the wrong dimension (0, i.e. a scalar) to the Unit Delay block output. In fact, for some reason, if the MATLAB Function is executed before the Unit Delay block, the function propagates `u_nm1` to `y_n` while `u_nm1` is still = 0, giving a scalar dimension to `y_n`.

The issue was still present with a Memory block replacing the Unit Delay. This couldn't be solved by forcing the sample time as we want this block to inherit the sample time of the model/system where it is inserted, and we wish to conserve the same block interface as the old "Holder" block.

For avoiding this issue, we came up with an alternative described below.

## Second and Final Iteration

<img width="631" alt="image" src="https://user-images.githubusercontent.com/6848872/118652727-29b52d80-b7e7-11eb-8c8b-a19d29e4b581.png">

The initial value of the IC (Initial Condition) block is set to 1 (scalar). The initial condition of the Memory block is `0`. All blocks have an inherited sample time. This design work for scalars or vector inputs of any size.

**Comment by nunoguedelha** [comment]
CC @diegoferigo @traversaro

**Comment by nunoguedelha** [comment]
CC @gabrielenava @CarlottaSartore

**Comment by nunoguedelha** [comment]
@traversaro , shall I PR this t `devel` or `master`? I would say `master since it's a fix on an existing commonly used block. Then we can merge master to devel with the newly added documentation updates.

**Comment by nunoguedelha** [comment]
CC @Giulero

**Comment by traversaro** [comment]
> 
> 
> @traversaro , shall I PR this t `devel` or `master`? I would say `master since it's a fix on an existing commonly used block. Then we can merge master to devel with the newly added documentation updates.

Yes, I would say master make sense.
