### ISSUE TITLE
Setup a gitattributes file? 

### ISSUE THREAD

**Issue by traversaro** [robotology/WB-Toolbox#48]
Mathworks maintains some interesting documentation related to how to store Simulink models in a git repository, see https://it.mathworks.com/help/simulink/ug/set-up-git-source-control.html . 
Perhaps it could make sense to follow some of their advices in this repo (and perhaps also in other repos, such as the controllers one @gabrielenava  ).

**Comment by francesco-romano** [comment]
Thanks
Done in 3f8895ab20197c6d05821b8ddd4bf4607dafd363

**Comment by DanielePucci** [comment]
@S-Dafarra @pi-q @diegoferigo
