### ISSUE TITLE
Clarification on how Holder block works 

### ISSUE THREAD

**Issue by gabrielenava** [robotology/WB-Toolbox#58]
I did the following test: a ramp signal (starting ramp value: 10) is sent into a subsystem, containing an HOLDER block. Every 2 seconds, the subsystem containing the HOLDER is enabled/disabled for a period of 1s each. See pictures attached.

![screenshot from 2017-10-26 11-50-39](https://user-images.githubusercontent.com/12396934/32046655-f5772a68-ba43-11e7-8f39-525d77b76ace.png)

Inside the subsystem:

![screenshot from 2017-10-26 11-52-01](https://user-images.githubusercontent.com/12396934/32046715-1d903f9e-ba44-11e7-849f-60087bb56f71.png)

These are the output: (Simulation time: 30s)

- Signal sent to the ENABLE block:

![screenshot from 2017-10-26 11-54-13](https://user-images.githubusercontent.com/12396934/32046852-7e32cd44-ba44-11e7-93f6-96da10684327.png)

- Ramp signal (no HOLDER)

![screenshot from 2017-10-26 11-54-30](https://user-images.githubusercontent.com/12396934/32046876-92ba9332-ba44-11e7-98a8-51adbb9fda07.png)

-  **Ramp signal passing through the HOLDER block**

![screenshot from 2017-10-26 11-54-46](https://user-images.githubusercontent.com/12396934/32046903-acf555de-ba44-11e7-834f-d857dba68de0.png)

Now we know that the output of HOLDER block **will always be the first value sent to the block**. Maybe this may be an issue for some applications.

**Comment by francesco-romano** [comment]
Thanks @gabrielenava 
I think that it may be worthwhile to move the implementation of the Holder block to c++ (the implementation is trivial).

Currently blocked by #46

**Comment by S-Dafarra** [comment]
This is not a problem of Holder block, but rather it is an intended behavior of the ``Enable`` Simulink block. 
If you select ``reset`` from the drop menu in the options of the ``Enable`` block, the internal state of the ``Holder`` block is reset when enabled, thus changing the value of the ``Holder`` with the new one.
![image](https://user-images.githubusercontent.com/18591940/32056938-37bceee0-ba66-11e7-9950-a070c34fa993.png)

**Comment by francesco-romano** [comment]
Thanks @S-Dafarra.
I knew about that option, but I don't know if @gabrielenava tried it. @gabrielenava can you try if the holder block still exhibits the same problem with this option changed?

**Comment by gabrielenava** [comment]
No it doesn't. I didn't know about this option, changing it solves the issue.

**Comment by francesco-romano** [comment]
Great. For the time being this can remain as simple matlab code if it is compatible with code generation
