### ISSUE TITLE
Dropped support of multiple configuration for SetLowLevelPid block

### ISSUE THREAD

**Issue by diegoferigo** [robotology/WB-Toolbox#61]
The `WB-Toolbox 3.0`, which will be released in the next weeks, dropped the support of changing in real-time the gains of the low level PIDs.

With the `2.0` version, it was possible specifying in a file multiple configurations. In the newest version, instead, only one configuration is supported, and it might be used to set new gains before the simulation runs, and to reset to the default ones when it finishes.

If any user need this feature again, please ping us commenting this issue.

**Comment by traversaro** [comment]
cc @robotology/codyco-developers @hu-yue
