### ISSUE TITLE
Test backwards compatibility of WB-Toolbox 3.0

### ISSUE THREAD

**Issue by diegoferigo** [robotology/wb-toolbox#66]
PR https://github.com/robotology/WB-Toolbox/pull/56 was tested on the following system:

* Ubuntu 17.04 (Zesty Zapus)
* Matlab 9.2 (2017a), Simulink (8.9)
* gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)
* clang version 4.0.0-1ubuntu1 (tags/RELEASE_400/rc1)

Here below a list of issues found during the tests.

### 1. Properties size check of Matlab classes

- [x] [WBToolboxConfig.m](https://github.com/diegoferigo/WB-Toolbox/blob/47f3b5a83f8f47214df0aa8c75174cac382324fb/toolbox/matlab/%2BWBToolbox/WBToolboxConfig.m#L10-L24)
- [x] [WBTPIDConfig.m](https://github.com/diegoferigo/WB-Toolbox/blob/47f3b5a83f8f47214df0aa8c75174cac382324fb/toolbox/matlab/%2BWBToolbox/WBTPIDConfig.m#L20-L23)
- [x] [PID.m](https://github.com/diegoferigo/WB-Toolbox/blob/47f3b5a83f8f47214df0aa8c75174cac382324fb/toolbox/matlab/%2BWBToolbox/PID.m#L18-L21)

### 2. Apices

- [x] [WBToolboxConfig](https://github.com/diegoferigo/WB-Toolbox/blob/47f3b5a83f8f47214df0aa8c75174cac382324fb/toolbox/matlab/%2BWBToolbox/WBToolboxConfig.m#L119): from `"'"` to `''''`

## C++

- [x] [Curly braket tuple initialization](https://github.com/diegoferigo/WB-Toolbox/blob/47f3b5a83f8f47214df0aa8c75174cac382324fb/toolbox/src/SetLowLevelPID.cpp#L123) fails on gcc 5.4 / Ubuntu 16.04

**Comment by traversaro** [comment]
As whole-body-controllers have been ported successfully, I guess this was solved, right @diegoferigo ?

**Comment by diegoferigo** [comment]
Yes, closing. It would have been nice testing it on other Ubuntu versions and maybe Windows, but let's do it with the most recent releases if needed.
