### ISSUE TITLE
Yarp port timeout

### ISSUE THREAD

**Issue by diegoferigo** [robotology/WB-Toolbox#68]
Using the _YarpRead_ block in **Blocking Read** configuration, if no data is received the whole Simulink (and Matlab) get stuck forever and they must be manually killed.

A timeout capability should be added, and this should generate an error. In this way the simulation would stop smoothly.

@S-Dafarra

**Comment by diegoferigo** [comment]
@S-Dafarra Temporary branch based on the current `master`:

https://github.com/diegoferigo/WB-Toolbox/tree/yarpReadPortTimeout

**Comment by S-Dafarra** [comment]
Thanks! I will test it right away!

**Comment by S-Dafarra** [comment]
It seems to be working as expected!

**Comment by diegoferigo** [comment]
Fixed by #74. @S-Dafarra Let me know if you face any issue. Now you can specify the timeout from _Yarp read_'s mask.
