### ISSUE TITLE
Unit of 'Reference speed' measurement in 'Set references' block

### ISSUE THREAD

**Issue by vibhoraggarwal** [robotology/wb-toolbox#75]
It is not clear on first sight that what is the unit of measurement for `reference speed` in the block. Mentioning of the unit in the text would be much convenient.
![image](https://user-images.githubusercontent.com/19661841/36483606-e89560dc-1716-11e8-8be3-6b69db928216.png)

**Comment by francesco-romano** [comment]
Just be careful that from what I understood [in the code](https://github.com/robotology/wb-toolbox/blob/WB3.0/toolbox/src/SetReferences.cpp#L140) the velocity is not converted from `rad/s` to `deg/s` making the toolbox not consistent (reference positions and velocities are in radians, but the velocity for the trajectory generator is in degrees per seconds).

**Comment by diegoferigo** [comment]
Fixed in https://github.com/robotology/wb-toolbox/issues/110
