### ISSUE TITLE
`GetLimit` block shows wrong max velocity value

### ISSUE THREAD

**Issue by vibhoraggarwal** [robotology/wb-toolbox#80]
`Get Limit` block shows the max velocity to the order of 10^4 

cc: @diegoferigo

**Comment by diegoferigo** [comment]
If you are using as source the `ControlBoard`, we should check what is stored in the xml configuration stored in https://github.com/robotology/robots-configuration. As far as I know, only the position is updated by time to time.

**Comment by diegoferigo** [comment]
Fixed in https://github.com/robotology/wb-toolbox/issues/110
